//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace d3xp_arcadenet.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("d3xp_arcadenet.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version 2
        ///// entity 0
        ///{
        ///&quot;classname&quot; &quot;worldspawn&quot;
        ///&quot;def_player&quot; &quot;d3xp_player_doommarine&quot;
        ///&quot;call&quot; &quot;map_erebus3::main&quot;
        ///// primitive 0
        ///{
        /// brushDef3
        /// {
        ///  ( 0 0 -1 1072 ) ( ( 0.0625 0 0 ) ( 0 0.0625 0 ) ) &quot;textures/common/clip&quot; 0 0 0
        ///  ( -0 0 1 -1200 ) ( ( 0.0625 0 0 ) ( 0 0.0625 0 ) ) &quot;textures/common/clip&quot; 0 0 0
        ///  ( -0 -1 -0 -1724 ) ( ( 0.0625 0 0 ) ( 0 0.0625 0 ) ) &quot;textures/common/clip&quot; 0 0 0
        ///  ( 1 0 0 1472 ) ( ( 0.0625 0 0 ) ( 0 0.0625 0 ) ) &quot;textures/common/clip&quot; 0 0 0
        ///  ( -0 1 0 1664 ) ( ( 0.06 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string erebus3 {
            get {
                return ResourceManager.GetString("erebus3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version 2
        ///// entity 0
        ///{
        ///&quot;classname&quot; &quot;worldspawn&quot;
        ///&quot;def_player&quot; &quot;d3xp_player_doommarine&quot;
        ///&quot;call&quot; &quot;map_erebus4::main&quot;
        ///// primitive 0
        ///{
        /// brushDef3
        /// {
        ///  ( 0 -0 1 64 ) ( ( 0.015625 0 0 ) ( 0 0.015625 0 ) ) &quot;textures/base_wall/lfwall27b&quot; 0 0 0
        ///  ( -1 0 0 -1344 ) ( ( 0.015625 0 -0.5 ) ( 0 0.015625 0 ) ) &quot;textures/base_wall/lfwall27a&quot; 0 0 0
        ///  ( -0 -0 -1 -80 ) ( ( 0.015625 0 -0.5 ) ( 0 0.015625 0.5 ) ) &quot;textures/base_wall/lfwall27a&quot; 0 0 0
        ///  ( 0 -1 0 -480 ) ( ( 0.015625 0 -1 ) ( 0 0.015625 0 ) ) &quot;textures/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string erebus4 {
            get {
                return ResourceManager.GetString("erebus4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version 2
        ///// entity 0
        ///{
        ///&quot;classname&quot; &quot;worldspawn&quot;
        ///&quot;def_player&quot; &quot;d3xp_player_doommarine&quot;
        ///&quot;call&quot; &quot;map_phobos2::main&quot;
        ///// primitive 0
        ///{
        /// brushDef3
        /// {
        ///  ( 0 0 -1 -1024 ) ( ( -0.0000000056 0.0312500037 -45.4999847412 ) ( 0.0312500037 0.0000000056 -131.0000152588 ) ) &quot;textures/common/caulk&quot; 0 0 0
        ///  ( -0 0 1 992 ) ( ( -0.0052083405 0.0000000006 8.666680336 ) ( -0.0000000009 -0.0078124958 -15.7499895096 ) ) &quot;textures/base_wall/lfwall26&quot; 0 0 0
        ///  ( 1 0.0000001788 -0 2015.9998779297 ) ( ( 0.0312500112 0 -193 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string phobos2 {
            get {
                return ResourceManager.GetString("phobos2", resourceCulture);
            }
        }
    }
}
